# server/docker/Dockerfile.java
FROM eclipse-temurin:21-jdk-jammy

RUN useradd -m runner
WORKDIR /work
USER runner

# cd to docker folder
# build command: docker build -t omni-runner:java ./java

#eg run command: 